version: '3.8'
services:
  x-men:
    container_name: x-men
    image: camilogo89/appfunction:latest
    restart: always
    environment:
      MongoConnectionString: mongodb://x-men-data-base:tYxrPbk5kQsgtBxCQS3m33cdqsRlQRgPdFqOYDZncSBHpsCcmwQscGhcEa11VkcMZpCB4W4pnjaa5IAJdjaDtQ==@x-men-data-base.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@x-men-data-base@
      MongoDbName: x-men
      ServiceBusConnection: Endpoint=sb://x-men-event-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=BsKBrsNW4AhCkyM/7wqu5R98UX1i3RU7QQs5w/BN+ek=
    ports:
      - "800:80"
    